services:
  ollama:
    image: ollama/ollama
    container_name: ollama-container
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/ .ollama
    entrypoint: >
      sh -c "ollama serve & sleep 5 && ollama pull gemma:2b && ollama pull llama3:8b && ollama pull deepseek-r1:1.5b && ollama pull gpt-oss:20b && tail -f /dev/null"
  
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi-ollama-image:latest
    container_name: fastapi-ollama-container
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434

volumes:
  ollama-data: